from __future__ import annotations

from typing import Any, Dict, List

from app.modules.pricing.schemas import PricingSeedStats


WEBSITE_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_001",
        "code": "essential_web",
        "productType": "website",
        "tier": "essential",
        "name": "Essential Web",
        "description": "Plan website essential con variantes core.",
        "basePrice": 7990,
        "basePriceMonthly": 7990,
        "basePriceYearly": 79990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_002",
        "code": "plus_web",
        "productType": "website",
        "tier": "plus",
        "name": "Plus Web",
        "description": "Plan website plus con variantes core y advanced.",
        "basePrice": 19990,
        "basePriceMonthly": 19990,
        "basePriceYearly": 199990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_003",
        "code": "pro_web",
        "productType": "website",
        "tier": "pro",
        "name": "Pro Web",
        "description": "Plan website pro con acceso completo a variantes premium.",
        "basePrice": 49990,
        "basePriceMonthly": 49990,
        "basePriceYearly": 499990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_004",
        "code": "custom_web",
        "productType": "website",
        "tier": "custom",
        "name": "Web Personalizada",
        "description": "Plan custom website con implementacion personalizada.",
        "basePrice": 250000,
        "basePriceMonthly": 250000,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

INVITATION_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_005",
        "code": "essential_pdf",
        "productType": "invitation",
        "tier": "essential",
        "name": "Essential PDF",
        "description": "Invitacion base en formato PDF.",
        "basePrice": 2990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_006",
        "code": "plus_invitation",
        "productType": "invitation",
        "tier": "plus",
        "name": "Plus Web Invitation",
        "description": "Invitacion web con modulos avanzados.",
        "basePrice": 7990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_007",
        "code": "pro_invitation",
        "productType": "invitation",
        "tier": "pro",
        "name": "Pro Experience Invitation",
        "description": "Invitacion experience con variantes premium incluidas.",
        "basePrice": 19990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_008",
        "code": "custom_invitation",
        "productType": "invitation",
        "tier": "custom",
        "name": "Invitación Personalizada",
        "description": "Invitacion personalizada con acceso completo.",
        "basePrice": 80000,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

PLAN_SEEDS = WEBSITE_PLAN_SEEDS + INVITATION_PLAN_SEEDS


def _variant(
    variant_code: str,
    name: str,
    variant_tier: str,
    product_type: str,
    sort_order: int,
    description: str = "",
    extra_price: int = 0,
) -> Dict[str, Any]:
    included_in_plans = {
        "core": ["essential", "plus", "pro"],
        "advanced": ["plus", "pro"],
        "premium": ["pro"],
    }[variant_tier]
    can_be_extra_in_plans = {
        "core": [],
        "advanced": [],
        "premium": ["plus"],
    }[variant_tier]
    resolved_extra_price = extra_price
    if variant_tier == "premium" and resolved_extra_price <= 0:
        resolved_extra_price = 3990 if product_type == "website" else 1990
    return {
        "variantCode": variant_code,
        "name": name,
        "description": description,
        "variantTier": variant_tier,
        "active": True,
        "includedInPlans": included_in_plans,
        "canBeExtraInPlans": can_be_extra_in_plans,
        "extraPrice": resolved_extra_price,
        "currency": "CLP",
        "sortOrder": sort_order,
    }


def _component(
    component_id: str,
    component_code: str,
    product_type: str,
    component_tier: str,
    sort_order: int,
    variants: List[Dict[str, Any]],
    description: str = "",
    category_code: str | None = None,
) -> Dict[str, Any]:
    return {
        "id": component_id,
        "componentCode": component_code,
        "productType": product_type,
        "categoryCode": category_code or component_code,
        "componentTier": component_tier,
        "name": component_code.replace("_", " ").replace("Beforeafter", "BeforeAfter").title(),
        "description": description,
        "active": True,
        "variants": variants,
        "sortOrder": sort_order,
    }


COMPONENT_SEEDS: List[Dict[str, Any]] = [
    _component("comp_001", "navigation", "website", "core", 1, [_variant("navigation-variant-a", "Navigation A", "core", "website", 1)]),
    _component("comp_002", "hero", "website", "core", 2, [_variant("hero-a", "Hero A", "core", "website", 1), _variant("hero-variant-a", "Hero Variant A", "core", "website", 2), _variant("hero-premium-video", "Hero Premium Video", "premium", "website", 8)]),
    _component("comp_003", "projects", "website", "advanced", 3, [_variant("projects-variant-a", "Projects A", "advanced", "website", 1)]),
    _component("comp_004", "beforeAfter", "website", "advanced", 4, [_variant("beforeAfter-variant-a", "Before After A", "advanced", "website", 1)]),
    _component("comp_005", "services", "website", "core", 5, [_variant("services-variant-a", "Services A", "core", "website", 1)]),
    _component("comp_006", "process", "website", "advanced", 6, [_variant("process-variant-a", "Process A", "advanced", "website", 1)]),
    _component("comp_007", "socialProof", "website", "advanced", 7, [_variant("socialProof-variant-a", "Social Proof A", "advanced", "website", 1)]),
    _component("comp_008", "branches", "website", "premium", 8, [_variant("branches-variant-a", "Branches A", "premium", "website", 1)]),
    _component("comp_009", "whatsappFloating", "website", "core", 9, [_variant("whatsappFloating-variant-a", "WhatsApp Floating A", "core", "website", 1)]),
    _component("comp_010", "content", "website", "core", 10, [_variant("content-variant-a", "Content A", "core", "website", 1), _variant("content-variant-b", "Content B", "advanced", "website", 2)]),
    _component("comp_011", "leadForm", "website", "advanced", 11, [_variant("leadForm-variant-a", "Lead Form A", "core", "website", 1)]),
    _component("comp_012", "footer", "website", "core", 12, [_variant("footer-variant-a", "Footer A", "core", "website", 1)]),
    _component("comp_013", "intro", "invitation", "core", 1, [_variant("intro-a", "Intro A", "core", "invitation", 1)]),
    _component("comp_014", "hero", "invitation", "core", 2, [_variant("hero-a", "Hero A", "core", "invitation", 1), _variant("hero-premium-video", "Hero Premium Video", "premium", "invitation", 8)]),
    _component("comp_015", "story", "invitation", "advanced", 3, [_variant("story-variant-a", "Story A", "advanced", "invitation", 1)]),
    _component("comp_016", "details", "invitation", "core", 4, [_variant("details-variant-a", "Details A", "core", "invitation", 1)]),
    _component("comp_017", "gallery", "invitation", "advanced", 5, [_variant("gallery-variant-a", "Gallery A", "advanced", "invitation", 1)]),
    _component("comp_018", "countdown", "invitation", "advanced", 6, [_variant("countdown-variant-a", "Countdown A", "advanced", "invitation", 1)]),
    _component("comp_019", "map", "invitation", "core", 7, [_variant("map-variant-a", "Map A", "core", "invitation", 1)]),
    _component("comp_020", "rsvp", "invitation", "core", 8, [_variant("rsvp-variant-a", "RSVP A", "core", "invitation", 1)]),
    _component("comp_021", "timeline", "invitation", "advanced", 9, [_variant("timeline-variant-a", "Timeline A", "advanced", "invitation", 1)]),
    _component("comp_022", "faq", "invitation", "advanced", 10, [_variant("faq-variant-a", "FAQ A", "advanced", "invitation", 1)]),
    _component("comp_023", "footer", "invitation", "core", 11, [_variant("footer-variant-a", "Footer A", "core", "invitation", 1)]),
]


TEMPLATE_CATEGORY_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "cat_001",
        "productType": "website",
        "categoryCode": "construction",
        "name": "Construcción",
        "description": "Templates para constructoras, obras y servicios relacionados.",
        "active": True,
        "sortOrder": 1,
        "allowedComponentCodes": ["navigation", "hero", "projects", "beforeAfter", "services", "process", "socialProof", "branches", "whatsappFloating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_002",
        "productType": "website",
        "categoryCode": "beauty",
        "name": "Belleza",
        "description": "Templates para belleza y bienestar.",
        "active": True,
        "sortOrder": 2,
        "allowedComponentCodes": ["navigation", "hero", "services", "socialProof", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_003",
        "productType": "website",
        "categoryCode": "technical_services",
        "name": "Servicios técnicos",
        "description": "Templates para servicios tecnicos y mantenimiento.",
        "active": True,
        "sortOrder": 3,
        "allowedComponentCodes": ["navigation", "hero", "services", "process", "socialProof", "branches", "whatsappFloating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_004",
        "productType": "website",
        "categoryCode": "restaurant",
        "name": "Restaurante",
        "description": "Templates para gastronomia.",
        "active": True,
        "sortOrder": 4,
        "allowedComponentCodes": ["navigation", "hero", "gallery", "services", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_005",
        "productType": "website",
        "categoryCode": "portfolio",
        "name": "Portafolio",
        "description": "Templates para profesionales creativos.",
        "active": True,
        "sortOrder": 5,
        "allowedComponentCodes": ["navigation", "hero", "projects", "gallery", "socialProof", "content", "footer"],
    },
    {
        "id": "cat_006",
        "productType": "website",
        "categoryCode": "corporate",
        "name": "Corporativo",
        "description": "Templates para empresas.",
        "active": True,
        "sortOrder": 6,
        "allowedComponentCodes": ["navigation", "hero", "projects", "beforeAfter", "services", "process", "socialProof", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_007",
        "productType": "website",
        "categoryCode": "health",
        "name": "Salud",
        "description": "Templates para salud y bienestar.",
        "active": True,
        "sortOrder": 7,
        "allowedComponentCodes": ["navigation", "hero", "services", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_008",
        "productType": "website",
        "categoryCode": "education",
        "name": "Educación",
        "description": "Templates para educacion y cursos.",
        "active": True,
        "sortOrder": 8,
        "allowedComponentCodes": ["navigation", "hero", "services", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_009",
        "productType": "invitation",
        "categoryCode": "wedding",
        "name": "Wedding",
        "description": "Templates para bodas.",
        "active": True,
        "sortOrder": 1,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "countdown", "map", "rsvp", "timeline", "faq", "footer"],
    },
    {
        "id": "cat_010",
        "productType": "invitation",
        "categoryCode": "birthday",
        "name": "Birthday",
        "description": "Templates para cumpleaños.",
        "active": True,
        "sortOrder": 2,
        "allowedComponentCodes": ["intro", "hero", "details", "gallery", "countdown", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_011",
        "productType": "invitation",
        "categoryCode": "baby_shower",
        "name": "Baby shower",
        "description": "Templates para baby shower.",
        "active": True,
        "sortOrder": 3,
        "allowedComponentCodes": ["intro", "hero", "details", "gallery", "countdown", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_012",
        "productType": "invitation",
        "categoryCode": "graduation",
        "name": "Graduation",
        "description": "Templates para graduaciones.",
        "active": True,
        "sortOrder": 4,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_013",
        "productType": "invitation",
        "categoryCode": "corporate_event",
        "name": "Corporate event",
        "description": "Templates para eventos corporativos.",
        "active": True,
        "sortOrder": 5,
        "allowedComponentCodes": ["intro", "hero", "details", "timeline", "map", "rsvp", "faq", "footer"],
    },
    {
        "id": "cat_014",
        "productType": "invitation",
        "categoryCode": "baptism",
        "name": "Baptism",
        "description": "Templates para bautizos.",
        "active": True,
        "sortOrder": 6,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "map", "rsvp", "footer"],
    },
]


GENERAL_EXTRA_SEEDS: List[Dict[str, Any]] = [
    {"code": "custom_domain", "name": "Dominio propio", "productType": "website", "price": 1990, "priceMonthly": 1990, "currency": "CLP"},
    {"code": "extra_image", "name": "Imagen extra", "productType": "website", "price": 190, "priceMonthly": 190, "currency": "CLP"},
    {"code": "extra_video", "name": "Video extra", "productType": "website", "price": 990, "priceMonthly": 990, "currency": "CLP"},
    {"code": "premium_hero", "name": "Hero Premium", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "immersive_video", "name": "Video inmersivo premium", "productType": "website", "price": 3990, "priceMonthly": 3990, "currency": "CLP"},
    {"code": "dashboard_admin", "name": "Dashboard administrador", "productType": "website", "price": 4990, "priceMonthly": 4990, "currency": "CLP"},
    {"code": "analytics", "name": "Analytics", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "advanced_seo", "name": "SEO avanzado", "productType": "website", "price": 9990, "priceMonthly": 9990, "currency": "CLP"},
    {"code": "mercadopago", "name": "Integración MercadoPago", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "transbank", "name": "Integración Transbank", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "priority_support", "name": "Soporte prioritario", "productType": "website", "price": 7990, "priceMonthly": 7990, "currency": "CLP"},
    {"code": "public_url_pdf", "name": "URL pública para PDF", "productType": "invitation", "price": 1990, "currency": "CLP"},
    {"code": "extra_video_invitation", "name": "Video extra", "productType": "invitation", "price": 1490, "currency": "CLP"},
    {"code": "dashboard_invitation", "name": "Dashboard administrador", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "trivia_game", "name": "Trivia pareja", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "puzzle_game", "name": "Puzzle", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "roulette_game", "name": "Ruleta", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "mini_adventure_game", "name": "Mini aventura", "productType": "invitation", "price": 5990, "currency": "CLP"},
    {"code": "custom_domain_invitation", "name": "Dominio propio", "productType": "invitation", "price": 1990, "priceMonthly": 1990, "currency": "CLP"},
    {"code": "extra_guests_50", "name": "50 invitados extra", "productType": "invitation", "price": 990, "currency": "CLP"},
    {"code": "advanced_rsvp", "name": "RSVP avanzado", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "guest_analytics", "name": "Analytics invitados", "productType": "invitation", "price": 2990, "currency": "CLP"},
]


def empty_seed_stats() -> PricingSeedStats:
    return PricingSeedStats()
