from __future__ import annotations

from typing import Any, Dict, List

from app.modules.pricing.schemas import PricingSeedStats


WEBSITE_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_001",
        "code": "website_essential",
        "productType": "website",
        "tier": "essential",
        "name": "Essential",
        "description": "Landing simple para presencia digital basica.",
        "basePrice": 24990,
        "durationMonths": 6,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_002",
        "code": "website_plus",
        "productType": "website",
        "tier": "plus",
        "name": "Plus",
        "description": "Website comercial con mas secciones y componentes premium.",
        "basePrice": 49990,
        "durationMonths": 6,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_003",
        "code": "website_pro",
        "productType": "website",
        "tier": "pro",
        "name": "Pro",
        "description": "Experiencia web avanzada con componentes de alto impacto.",
        "basePrice": 89990,
        "durationMonths": 12,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_004",
        "code": "website_custom",
        "productType": "website",
        "tier": "custom",
        "name": "Custom",
        "description": "Propuesta a medida para necesidades especiales.",
        "basePrice": 0,
        "durationMonths": 12,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

INVITATION_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_005",
        "code": "invitation_essential",
        "productType": "invitation",
        "tier": "essential",
        "name": "Essential",
        "description": "Invitacion digital simple con lo esencial para compartir.",
        "basePrice": 14990,
        "durationMonths": 6,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_006",
        "code": "invitation_plus",
        "productType": "invitation",
        "tier": "plus",
        "name": "Plus",
        "description": "Invitacion con mas personalizacion y modulos adicionales.",
        "basePrice": 24990,
        "durationMonths": 6,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_007",
        "code": "invitation_pro",
        "productType": "invitation",
        "tier": "pro",
        "name": "Pro",
        "description": "Invitacion premium con juegos, analytics y extras avanzados.",
        "basePrice": 39990,
        "durationMonths": 12,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_008",
        "code": "invitation_custom",
        "productType": "invitation",
        "tier": "custom",
        "name": "Custom",
        "description": "Configuracion flexible para celebraciones con requerimientos especiales.",
        "basePrice": 0,
        "durationMonths": 12,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

PLAN_SEEDS = WEBSITE_PLAN_SEEDS + INVITATION_PLAN_SEEDS


def _variant(variant_code: str, name: str, description: str) -> Dict[str, Any]:
    return {
        "variantCode": variant_code,
        "name": name,
        "description": description,
        "active": True,
    }


COMPONENT_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "comp_001",
        "componentCode": "menu_header",
        "productType": "website",
        "name": "Menu Header",
        "description": "Cabecera principal con navegacion del sitio.",
        "active": True,
        "variants": [_variant("NAV-Classic", "Clasico", "Menu superior tradicional.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 1,
    },
    {
        "id": "comp_002",
        "componentCode": "hero_basic",
        "productType": "website",
        "name": "Hero Basic",
        "description": "Hero simple para presentar propuesta principal.",
        "active": True,
        "variants": [_variant("H1-Basic-Focus", "Foco simple", "Hero con texto e imagen principal.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 2,
    },
    {
        "id": "comp_003",
        "componentCode": "hero_pro",
        "productType": "website",
        "name": "Hero Pro",
        "description": "Hero con video, capas y animaciones.",
        "active": True,
        "variants": [_variant("H1-Modern-Impact", "Impacto moderno", "Diseno de alto impacto con imagen o video.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 9990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 3,
    },
    {
        "id": "comp_004",
        "componentCode": "project_gallery",
        "productType": "website",
        "name": "Project Gallery",
        "description": "Galeria para proyectos o portafolio.",
        "active": True,
        "variants": [_variant("PG-Grid", "Grid", "Mosaico de proyectos destacados.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 6990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 4,
    },
    {
        "id": "comp_005",
        "componentCode": "before_after",
        "productType": "website",
        "name": "Before / After",
        "description": "Comparador visual antes y despues.",
        "active": True,
        "variants": [_variant("BA-Slider", "Slider", "Comparador interactivo deslizante.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 8990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 5,
    },
    {
        "id": "comp_006",
        "componentCode": "services",
        "productType": "website",
        "name": "Services",
        "description": "Bloque para listar servicios o especialidades.",
        "active": True,
        "variants": [_variant("SV-Cards", "Tarjetas", "Listado de servicios en tarjetas.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 6,
    },
    {
        "id": "comp_007",
        "componentCode": "process_timeline",
        "productType": "website",
        "name": "Process Timeline",
        "description": "Explica etapas de trabajo o servicio.",
        "active": True,
        "variants": [_variant("PT-Steps", "Pasos", "Linea de tiempo orientada a conversion.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 7,
    },
    {
        "id": "comp_008",
        "componentCode": "testimonials",
        "productType": "website",
        "name": "Testimonials",
        "description": "Prueba social con comentarios de clientes.",
        "active": True,
        "variants": [_variant("TS-Quotes", "Citas", "Tarjetas con testimonios destacados.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 8,
    },
    {
        "id": "comp_009",
        "componentCode": "client_logos",
        "productType": "website",
        "name": "Client Logos",
        "description": "Carrusel o grilla de marcas clientes.",
        "active": True,
        "variants": [_variant("CL-Strip", "Franja", "Cinta de logos con enfoque corporativo.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 3990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 9,
    },
    {
        "id": "comp_010",
        "componentCode": "branches",
        "productType": "website",
        "name": "Branches",
        "description": "Listado de sucursales o ubicaciones.",
        "active": True,
        "variants": [_variant("BR-MapList", "Mapa y lista", "Ubicaciones con informacion de contacto.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 6990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 10,
    },
    {
        "id": "comp_011",
        "componentCode": "immersive_video",
        "productType": "website",
        "name": "Immersive Video",
        "description": "Modulo audiovisual de alto impacto.",
        "active": True,
        "variants": [_variant("IV-FullBleed", "Full bleed", "Video inmersivo a pantalla completa.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 12990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 11,
    },
    {
        "id": "comp_012",
        "componentCode": "long_context",
        "productType": "website",
        "name": "Long Context",
        "description": "Seccion editorial larga para profundizar la propuesta.",
        "active": True,
        "variants": [_variant("LC-Editorial", "Editorial", "Bloque narrativo de lectura extendida.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 7990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 12,
    },
    {
        "id": "comp_013",
        "componentCode": "lead_form",
        "productType": "website",
        "name": "Lead Form",
        "description": "Formulario para captar prospectos.",
        "active": True,
        "variants": [_variant("LF-Contact", "Contacto", "Formulario de contacto optimizado para conversion.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 13,
    },
    {
        "id": "comp_014",
        "componentCode": "whatsapp_floating",
        "productType": "website",
        "name": "WhatsApp Floating",
        "description": "Boton flotante de WhatsApp.",
        "active": True,
        "variants": [_variant("WA-Floating", "Flotante", "Acceso rapido a conversacion directa.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 1990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 14,
    },
    {
        "id": "comp_015",
        "componentCode": "footer",
        "productType": "website",
        "name": "Footer",
        "description": "Pie de pagina comercial.",
        "active": True,
        "variants": [_variant("FO-Brand", "Marca", "Footer con marca, enlaces y contacto.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 15,
    },
    {
        "id": "comp_016",
        "componentCode": "invitation_cover",
        "productType": "invitation",
        "name": "Invitation Cover",
        "description": "Portada principal de la invitacion.",
        "active": True,
        "variants": [_variant("IC-Cinematic", "Cinematica", "Portada destacada con imagen principal.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 1,
    },
    {
        "id": "comp_017",
        "componentCode": "invitation_menu",
        "productType": "invitation",
        "name": "Invitation Menu",
        "description": "Menu de navegacion para la invitacion.",
        "active": True,
        "variants": [_variant("IM-Minimal", "Minimal", "Navegacion ligera para invitacion digital.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 1990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 2,
    },
    {
        "id": "comp_018",
        "componentCode": "invitation_timeline",
        "productType": "invitation",
        "name": "Invitation Timeline",
        "description": "Secuencia del evento o ceremonia.",
        "active": True,
        "variants": [_variant("IT-EventFlow", "Flujo del evento", "Linea temporal del gran dia.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 3,
    },
    {
        "id": "comp_019",
        "componentCode": "invitation_gallery",
        "productType": "invitation",
        "name": "Invitation Gallery",
        "description": "Galeria de fotos para la pareja o el evento.",
        "active": True,
        "variants": [_variant("IG-Memories", "Recuerdos", "Galeria emotiva con imagenes destacadas.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 3990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 4,
    },
    {
        "id": "comp_020",
        "componentCode": "countdown",
        "productType": "invitation",
        "name": "Countdown",
        "description": "Cuenta regresiva para el evento.",
        "active": True,
        "variants": [_variant("CD-Classic", "Clasico", "Contador visual del tiempo restante.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 2990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 5,
    },
    {
        "id": "comp_021",
        "componentCode": "music",
        "productType": "invitation",
        "name": "Music",
        "description": "Musica de fondo para la invitacion.",
        "active": True,
        "variants": [_variant("MU-Player", "Player", "Reproductor musical discreto.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 2990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 6,
    },
    {
        "id": "comp_022",
        "componentCode": "map_location",
        "productType": "invitation",
        "name": "Map Location",
        "description": "Mapa y acceso a la ubicacion del evento.",
        "active": True,
        "variants": [_variant("ML-Route", "Ruta", "Mapa con enlace directo a ubicacion.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 7,
    },
    {
        "id": "comp_023",
        "componentCode": "dresscode",
        "productType": "invitation",
        "name": "Dresscode",
        "description": "Indicaciones de vestimenta para los invitados.",
        "active": True,
        "variants": [_variant("DR-Notice", "Aviso", "Seccion clara de codigo de vestimenta.")],
        "includedInPlans": ["plus", "pro", "custom"],
        "canBeExtraInPlans": ["essential"],
        "extraPrice": 1990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 8,
    },
    {
        "id": "comp_024",
        "componentCode": "rsvp",
        "productType": "invitation",
        "name": "RSVP",
        "description": "Confirmacion de asistencia.",
        "active": True,
        "variants": [_variant("RSVP-Form", "Formulario", "Confirmacion integrada desde la invitacion.")],
        "includedInPlans": ["essential", "plus", "pro", "custom"],
        "canBeExtraInPlans": [],
        "extraPrice": 0,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 9,
    },
    {
        "id": "comp_025",
        "componentCode": "guest_groups",
        "productType": "invitation",
        "name": "Guest Groups",
        "description": "Segmentacion de invitados por grupo.",
        "active": True,
        "variants": [_variant("GG-Segments", "Segmentos", "Control de mensajes por grupo.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 10,
    },
    {
        "id": "comp_026",
        "componentCode": "personalized_messages",
        "productType": "invitation",
        "name": "Personalized Messages",
        "description": "Mensajes personalizados por invitado.",
        "active": True,
        "variants": [_variant("PM-Direct", "Directo", "Saludo individual dentro de la invitacion.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["essential", "plus"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 11,
    },
    {
        "id": "comp_027",
        "componentCode": "guest_unique_urls",
        "productType": "invitation",
        "name": "Guest Unique URLs",
        "description": "URLs unicas por invitado.",
        "active": True,
        "variants": [_variant("GU-Tracked", "Trackeadas", "Invitaciones individuales con enlace unico.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["plus"],
        "extraPrice": 6990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 12,
    },
    {
        "id": "comp_028",
        "componentCode": "admin_dashboard",
        "productType": "invitation",
        "name": "Admin Dashboard",
        "description": "Panel para administrar asistentes y respuestas.",
        "active": True,
        "variants": [_variant("AD-Overview", "Resumen", "Vista operativa de confirmaciones y gestion.")],
        "includedInPlans": ["pro", "custom"],
        "canBeExtraInPlans": ["plus"],
        "extraPrice": 7990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 13,
    },
    {
        "id": "comp_029",
        "componentCode": "guest_analytics",
        "productType": "invitation",
        "name": "Guest Analytics",
        "description": "Metricas de aperturas e interacciones.",
        "active": True,
        "variants": [_variant("GA-Insights", "Insights", "Panel de actividad de invitados.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["pro"],
        "extraPrice": 9990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 14,
    },
    {
        "id": "comp_030",
        "componentCode": "game_trivia",
        "productType": "invitation",
        "name": "Game Trivia",
        "description": "Juego tipo trivia para invitados.",
        "active": True,
        "variants": [_variant("GT-Quiz", "Quiz", "Preguntas personalizadas sobre la historia.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["plus", "pro"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 15,
    },
    {
        "id": "comp_031",
        "componentCode": "game_puzzle",
        "productType": "invitation",
        "name": "Game Puzzle",
        "description": "Mini juego de puzzle interactivo.",
        "active": True,
        "variants": [_variant("GP-Sliding", "Deslizante", "Puzzle ligero para experiencia ludica.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["plus", "pro"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 16,
    },
    {
        "id": "comp_032",
        "componentCode": "game_roulette",
        "productType": "invitation",
        "name": "Game Roulette",
        "description": "Ruleta interactiva para dinamicas del evento.",
        "active": True,
        "variants": [_variant("GR-Spin", "Spin", "Ruleta con premios o desafios.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["plus", "pro"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 17,
    },
    {
        "id": "comp_033",
        "componentCode": "game_story_adventure",
        "productType": "invitation",
        "name": "Game Story Adventure",
        "description": "Juego narrativo interactivo.",
        "active": True,
        "variants": [_variant("GSA-Story", "Historia", "Aventura corta basada en decisiones.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["pro"],
        "extraPrice": 6990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 18,
    },
    {
        "id": "comp_034",
        "componentCode": "ranking_top_5",
        "productType": "invitation",
        "name": "Ranking Top 5",
        "description": "Ranking compartido de respuestas o interacciones.",
        "active": True,
        "variants": [_variant("RT5-Leaderboard", "Leaderboard", "Ranking publico para dinamicas sociales.")],
        "includedInPlans": ["custom"],
        "canBeExtraInPlans": ["pro"],
        "extraPrice": 4990,
        "currency": "CLP",
        "unit": "component",
        "sortOrder": 19,
    },
]


def empty_seed_stats() -> PricingSeedStats:
    return PricingSeedStats()
