from __future__ import annotations

from typing import Any, Dict, List

from app.modules.pricing.schemas import PricingSeedStats


WEBSITE_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_001",
        "code": "essential_web",
        "productType": "website",
        "tier": "essential",
        "name": "Essential Web",
        "description": "Plan website essential con variantes core.",
        "basePrice": 7990,
        "basePriceMonthly": 7990,
        "basePriceYearly": 79990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_002",
        "code": "plus_web",
        "productType": "website",
        "tier": "plus",
        "name": "Plus Web",
        "description": "Plan website plus con variantes core y advanced.",
        "basePrice": 19990,
        "basePriceMonthly": 19990,
        "basePriceYearly": 199990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_003",
        "code": "pro_web",
        "productType": "website",
        "tier": "pro",
        "name": "Pro Web",
        "description": "Plan website pro con acceso completo a variantes premium.",
        "basePrice": 49990,
        "basePriceMonthly": 49990,
        "basePriceYearly": 499990,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_004",
        "code": "custom_web",
        "productType": "website",
        "tier": "custom",
        "name": "Web Personalizada",
        "description": "Plan custom website con implementacion personalizada.",
        "basePrice": 250000,
        "basePriceMonthly": 250000,
        "durationMonths": 1,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

INVITATION_PLAN_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "plan_005",
        "code": "essential_pdf",
        "productType": "invitation",
        "tier": "essential",
        "name": "Essential PDF",
        "description": "Invitacion base en formato PDF.",
        "basePrice": 2990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 1,
    },
    {
        "id": "plan_006",
        "code": "plus_invitation",
        "productType": "invitation",
        "tier": "plus",
        "name": "Plus Web Invitation",
        "description": "Invitacion web con modulos avanzados.",
        "basePrice": 7990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 2,
    },
    {
        "id": "plan_007",
        "code": "pro_invitation",
        "productType": "invitation",
        "tier": "pro",
        "name": "Pro Experience Invitation",
        "description": "Invitacion experience con variantes premium incluidas.",
        "basePrice": 19990,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 3,
    },
    {
        "id": "plan_008",
        "code": "custom_invitation",
        "productType": "invitation",
        "tier": "custom",
        "name": "Invitación Personalizada",
        "description": "Invitacion personalizada con acceso completo.",
        "basePrice": 80000,
        "durationMonths": 0,
        "currency": "CLP",
        "active": True,
        "sortOrder": 4,
    },
]

PLAN_SEEDS = WEBSITE_PLAN_SEEDS + INVITATION_PLAN_SEEDS


def _variant(
    variant_code: str,
    name: str,
    variant_tier: str,
    product_type: str,
    sort_order: int,
    description: str = "",
    extra_price: int = 0,
) -> Dict[str, Any]:
    included_in_plans = {
        "core": ["essential", "plus", "pro"],
        "advanced": ["plus", "pro"],
        "premium": ["pro"],
    }[variant_tier]
    can_be_extra_in_plans = {
        "core": [],
        "advanced": [],
        "premium": ["plus"],
    }[variant_tier]
    resolved_extra_price = extra_price
    if variant_tier == "premium" and resolved_extra_price <= 0:
        resolved_extra_price = 3990 if product_type == "website" else 1990
    return {
        "variantCode": variant_code,
        "name": name,
        "description": description,
        "variantTier": variant_tier,
        "active": True,
        "includedInPlans": included_in_plans,
        "canBeExtraInPlans": can_be_extra_in_plans,
        "extraPrice": resolved_extra_price,
        "currency": "CLP",
        "sortOrder": sort_order,
    }


def _component(
    component_id: str,
    component_code: str,
    product_type: str,
    component_tier: str,
    sort_order: int,
    variants: List[Dict[str, Any]],
    name: str | None = None,
    description: str = "",
    category_code: str | None = None,
) -> Dict[str, Any]:
    return {
        "id": component_id,
        "componentCode": component_code,
        "productType": product_type,
        "categoryCode": category_code or component_code,
        "componentTier": component_tier,
        "name": name or component_code.replace("_", " ").replace("Beforeafter", "BeforeAfter").title(),
        "description": description,
        "active": True,
        "variants": variants,
        "sortOrder": sort_order,
    }


COMPONENT_SEEDS: List[Dict[str, Any]] = [
    _component("comp_001", "navigation", "website", "core", 1, [
        _variant("N1", "Navegación superpuesta", "core", "website", 1),
        _variant("ME1-Overlay-Nav", "Navegación superpuesta", "core", "website", 2),
        _variant("N2", "Navegación dividida", "core", "website", 3),
        _variant("ME2-Split-Nav", "Navegación dividida", "core", "website", 4),
        _variant("N3", "Navegación fija minimalista", "core", "website", 5),
        _variant("ME3-Minimal-Sticky", "Navegación fija minimalista", "core", "website", 6),
        _variant("N4", "Tipografía cinética revelada", "advanced", "website", 7),
        _variant("MA1-Kinetic-Typography-Reveal", "Tipografía cinética revelada", "advanced", "website", 8),
        _variant("N5", "Neomorfismo invertido", "advanced", "website", 9),
        _variant("MA2-Neomorphic-Inverted", "Navegación neomórfica invertida", "advanced", "website", 10),
        _variant("N6", "Malla degradada distorsionada", "advanced", "website", 11),
        _variant("MA3-Distorted-Mesh-Gradient", "Malla degradada distorsionada", "advanced", "website", 12),
        _variant("M7", "Marco orgánico premium", "premium", "website", 13),
        _variant(
            "MP1-Organic-Premium-Frame",
            "Marco orgánico premium",
            "premium",
            "website",
            14,
            "Navegación premium superpuesta con frame orgánico.",
        ),
        _variant(
            "MP2-Breadcrumb-Multipage",
            "Menú multipágina con breadcrumb",
            "premium",
            "website",
            15,
            "Navegación premium con breadcrumb para sitios multipágina.",
        ),
        _variant(
            "MP3-Organic-Login",
            "Menú orgánico con inicio de sesión",
            "premium",
            "website",
            16,
            "Navegación premium orgánica con acceso de usuario.",
        ),
        _variant(
            "MP4-Musicians-Right-Drawer",
            "Menú plus lateral derecho",
            "premium",
            "website",
            17,
            "Navegación premium para músicos con menú fijo a la derecha y drawer lateral derecho en mobile.",
        ),
    ], name="Encabezado / Menú"),
    _component("comp_002", "hero", "website", "core", 2, [
        _variant("H1", "Impacto moderno", "core", "website", 1),
        _variant("HE1-Modern-Impact", "Impacto moderno", "core", "website", 2),
        _variant("H2", "Presentación de marca", "core", "website", 3),
        _variant("HE2-Split-Screen", "Pantalla dividida", "core", "website", 4),
        _variant("H3", "Portada editorial", "core", "website", 5),
        _variant("HE3-Parallax-Layered", "Parallax en capas", "core", "website", 6),
        _variant("H4", "Narrativa diagonal", "advanced", "website", 7),
        _variant("HA1-Multi-Layer-Kinetic-Parallax", "Parallax cinético multicapa", "advanced", "website", 8),
        _variant("H6", "Hero split interactivo", "advanced", "website", 9),
        _variant("HA2-Zoom-On-Scroll-Reveal", "Zoom con revelado al hacer scroll", "advanced", "website", 10),
        _variant("H7", "Hero cinemático", "advanced", "website", 11),
        _variant("HA3-Immersion-Typography-Tunnel", "Túnel tipográfico inmersivo", "advanced", "website", 12),
        _variant("H8", "Editorial con video subido", "premium", "website", 13),
        _variant("HP1-Editorial-Video-Upload", "Editorial con video subido", "premium", "website", 14),
        _variant("H9", "Hero inmersivo premium", "premium", "website", 15),
        _variant("HP2-Editorial-Video-Youtube", "Editorial con YouTube", "premium", "website", 16),
        _variant("HP3-Cinematic-Image-Frame", "Marco de imagen cinematográfico", "premium", "website", 17),
    ], name="Hero Dinámico", description="Sección principal de alto impacto."),
    _component("comp_003", "projects", "website", "core", 3, [
        _variant("G1", "Masonry Grid", "core", "website", 1),
        _variant("PE1-Masonry-Grid", "Cuadrícula tipo mosaico", "core", "website", 2),
        _variant("G2", "Tarjetas editoriales", "core", "website", 3),
        _variant("PE2-Parallax-Tiles-Reveal", "Baldosas con parallax", "core", "website", 4),
        _variant("G3", "Galería por columnas", "core", "website", 5),
        _variant("PE3-Interactive-Tabs", "Pestañas interactivas", "core", "website", 6),
        _variant("G4", "Filtro por categorías", "advanced", "website", 7),
        _variant("PA1-Infinite-Draggable-Grid", "Cuadrícula arrastrable infinita", "advanced", "website", 8),
        _variant("G5", "Carrusel de proyectos", "advanced", "website", 9),
        _variant("PA2-Full-Width-Slider", "Carrusel de ancho completo", "advanced", "website", 10),
        _variant("G6", "Showcase inmersivo", "premium", "website", 11),
        _variant("PA3-Liquid-Distortion-Hover", "Distorsión líquida al pasar", "advanced", "website", 12),
        _variant("G7", "Proyectos con storytelling", "premium", "website", 13),
        _variant("PP1-Smart-Sync-Reader", "Lector sincronizado inteligente", "premium", "website", 14),
    ], name="Proyectos / Portafolio"),
    _component("comp_004", "beforeAfter", "website", "core", 4, [
        _variant("BA1", "Slider clásico", "core", "website", 1),
        _variant("BAE1-Slider-Classic", "Deslizador clásico", "core", "website", 2),
        _variant("BA2", "Comparador vertical", "core", "website", 3),
        _variant("BAE2-Fade-Interaction", "Interacción por desvanecido", "core", "website", 4),
        _variant("BA3", "Antes y después compacto", "core", "website", 5),
        _variant("BAE3-Diagonal-Split", "División diagonal", "core", "website", 6),
        _variant("BA4", "Comparador expandido", "advanced", "website", 7),
        _variant("BAA1-Lens-Magnifier-Effect", "Efecto lupa", "advanced", "website", 8),
        _variant("BA5", "Comparador con captions", "advanced", "website", 9),
        _variant("BAA2-3D-Card-Flip", "Giro de tarjeta 3D", "advanced", "website", 10),
        _variant("BA6", "Antes y después premium", "premium", "website", 11),
        _variant("BAP1-Curtain-Reveal-Parallax", "Revelado tipo cortina con parallax", "premium", "website", 12),
    ], name="Antes y después"),
    _component("comp_005", "services", "website", "core", 5, [
        _variant("S1", "Glass Card", "core", "website", 1),
        _variant("SE1-Glass-Card", "Galería editorial", "core", "website", 2),
        _variant("S2", "Iconos centrados", "core", "website", 3),
        _variant("SE2-Blueprint-Style", "Ficha blueprint", "core", "website", 4),
        _variant("S3", "Lista de servicios", "core", "website", 5),
        _variant("SE3-Number-Focus", "Lista numerada", "core", "website", 6),
        _variant("S4", "Servicios con media", "advanced", "website", 7),
        _variant("SA1-Neomorphic-Hover-Depth", "Showcase interactivo", "advanced", "website", 8),
        _variant("S5", "Servicios desplegables", "advanced", "website", 9),
        _variant("SA2-Kinetic-Icon-Animation", "Pasarela interactiva", "advanced", "website", 10),
        _variant("S6", "Servicios comparativos", "advanced", "website", 11),
        _variant("SA3-Floating-3D-Layers", "Editorial alternado", "advanced", "website", 12),
        _variant("S7", "Servicios premium en columnas", "premium", "website", 13),
        _variant("SA4-Bento-Kinetic-Stack", "Bento visual", "advanced", "website", 14),
        _variant("S8", "Servicios con hover inmersivo", "premium", "website", 15),
        _variant("SP1-Dynamic-Path-Cards", "Carrusel cinematográfico", "premium", "website", 16),
        _variant("S9", "Servicios narrativa premium", "premium", "website", 17),
        _variant("SP2-Premium-Circle-Link-Canvas", "Lienzo circular premium", "premium", "website", 18),
    ], name="Servicios"),
    _component("comp_006", "process", "website", "core", 6, [
        _variant("T1", "Timeline simple", "core", "website", 1),
        _variant("TE1-Vertical-Snake", "Recorrido vertical", "core", "website", 2),
        _variant("T2", "Proceso numerado", "core", "website", 3),
        _variant("TE2-Horizontal-Steps", "Pasos horizontales", "core", "website", 4),
        _variant("T3", "Proceso expandible", "advanced", "website", 5),
        _variant("TA1-Circular-Orbit", "Órbita circular", "advanced", "website", 6),
        _variant("T4", "Timeline premium", "premium", "website", 7),
        _variant("TP1-Blueprint-Scanner", "Escáner blueprint", "premium", "website", 8),
    ], name="Timeline de procesos"),
    _component("comp_007", "socialProof", "website", "core", 7, [
        _variant("C1", "Testimonios en tarjetas", "core", "website", 1),
        _variant("PSE1-Infinite-Marquee", "Marquesina infinita", "core", "website", 2),
        _variant("C2", "Logotipos de clientes", "core", "website", 3),
        _variant("PSE2-Quote-Bubble", "Burbuja de cita", "core", "website", 4),
        _variant("C3", "Reseñas destacadas", "advanced", "website", 5),
        _variant("PSA1-Editorial-Float", "Editorial flotante", "advanced", "website", 6),
        _variant("C4", "Muro de confianza", "advanced", "website", 7),
        _variant("C5", "Prueba social premium", "premium", "website", 8),
        _variant("PSP1-Auto-Scroll-Rating-Marquee", "Rating marquee continuo", "premium", "website", 9),
        _variant("PSP2-Video-Grid", "Testimonios en video", "premium", "website", 10),
    ], name="Testimonios y logotipos"),
    _component("comp_008", "branches", "website", "premium", 8, [
        _variant("SUC1", "Sucursales y sedes", "premium", "website", 1),
        _variant("SUP1-Interactive-Location-Grid", "Grid de sedes interactivo", "premium", "website", 2),
    ], name="Sucursales y sedes"),
    _component("comp_009", "immersiveVideo", "website", "premium", 9, [
        _variant("VID1", "Video inmersivo premium", "premium", "website", 1),
        _variant("VIP1-Cinematic-Theater-Modal", "Theater modal cinematográfico", "premium", "website", 2),
    ], name="Video inmersivo"),
    _component("comp_010", "youtubeVideo", "website", "core", 10, [
        _variant("YT1", "Video YouTube", "core", "website", 1),
        _variant("YTE1-Embedded-Youtube", "Embed de YouTube", "core", "website", 2),
    ], name="Video YouTube"),
    _component("comp_011", "whatsapp_floating", "website", "core", 11, [
        _variant("WA1", "Botón flotante", "core", "website", 1),
        _variant("WAE1-Floating-Button", "Botón flotante", "core", "website", 2),
        _variant("WA2", "Flotante con texto", "core", "website", 3),
        _variant("WAE2-Floating-With-Label", "Flotante con texto", "core", "website", 4),
        _variant("WA3", "Ayuda acoplada al footer", "core", "website", 5),
        _variant("WAA1-Footer-Docked-Help", "Ayuda acoplada al footer", "advanced", "website", 6),
    ], name="WhatsApp flotante"),
    _component("comp_012", "blankCanvas", "website", "advanced", 12, [
        _variant("FREE1", "Canvas libre", "advanced", "website", 1),
        _variant("BCE1-Blank-Canvas", "Canvas libre", "core", "website", 2),
    ], name="Canvas libre"),
    _component("comp_013", "content", "website", "core", 13, [
        _variant("COE1-Focus-Reveal", "Revelado por foco", "core", "website", 1),
        _variant("N1", "Contenido base", "core", "website", 2),
        _variant("N2", "Contenido editorial", "advanced", "website", 3),
        _variant("COA1-Data-Wall", "Muro de datos", "advanced", "website", 4),
        _variant("COA2-Interactive-Blueprint-Glossary", "Glosario interactivo blueprint", "advanced", "website", 5),
        _variant("N3", "Contenido premium", "premium", "website", 6),
    ], name="Contenido"),
    _component("comp_014", "leadForm", "website", "advanced", 14, [
        _variant("Q1", "Formulario Lead Gen", "advanced", "website", 1),
        _variant("LFP1-Multi-Step", "Formulario por pasos", "premium", "website", 2),
        _variant("Q2", "Formulario conversión rápida", "advanced", "website", 3),
        _variant("LFP2-Map-Lead", "Mapa con captura de lead", "premium", "website", 4),
        _variant("LFP3-Conversational", "Conversacional", "premium", "website", 5),
        _variant("Q3", "Lead Gen premium", "premium", "website", 6),
        _variant("LFP4-Gamified-Cost-Calculator", "Calculadora gamificada de costo", "premium", "website", 7),
        _variant("Q4", "Lead scoring premium", "premium", "website", 8),
        _variant("Q5", "Formulario premium multipaso", "premium", "website", 9),
        _variant("LFP5-Step-by-Step-Modal-Reveal", "Modal paso a paso", "premium", "website", 10),
    ], name="Formulario Lead Gen"),
    _component("comp_015", "footer", "website", "core", 15, [
        _variant("FTE1-Industrial-Dark", "Industrial oscuro", "core", "website", 1),
        _variant("F1", "Footer clásico", "core", "website", 2),
        _variant("FTE2-Minimal-Clean", "Minimal limpio", "core", "website", 3),
        _variant("F2", "Footer compacto", "core", "website", 4),
        _variant("FTE3-Column-Big-Text", "Columnas con texto protagonista", "core", "website", 5),
        _variant("F3", "Footer de contacto", "core", "website", 6),
        _variant("F4", "Footer extendido", "advanced", "website", 7),
        _variant("FTA1-Particle-Background-Shader", "Fondo de partículas", "advanced", "website", 8),
        _variant("F5", "Footer con CTA", "advanced", "website", 9),
        _variant("FTA2-Kinetic-Typo-Marquee", "Tipografía cinética en marquesina", "advanced", "website", 10),
        _variant("FTA3-Reveal-on-Scroll-Total", "Revelado total al hacer scroll", "advanced", "website", 11),
        _variant("F6", "Footer premium editorial", "premium", "website", 12),
        _variant("FTP1-Corporate-Network-Hub", "Hub corporativo y redes", "premium", "website", 13),
        _variant("F7", "Footer premium expandido", "premium", "website", 14),
    ], name="Pie de página"),
    _component("comp_016", "intro", "invitation", "core", 1, [_variant("intro-a", "Intro A", "core", "invitation", 1)]),
    _component("comp_017", "hero", "invitation", "core", 2, [_variant("hero-a", "Hero A", "core", "invitation", 1), _variant("hero-premium-video", "Hero Premium Video", "premium", "invitation", 8)]),
    _component("comp_018", "story", "invitation", "advanced", 3, [_variant("story-variant-a", "Story A", "advanced", "invitation", 1)]),
    _component("comp_019", "details", "invitation", "core", 4, [_variant("details-variant-a", "Details A", "core", "invitation", 1)]),
    _component("comp_020", "gallery", "invitation", "advanced", 5, [_variant("gallery-variant-a", "Gallery A", "advanced", "invitation", 1)]),
    _component("comp_021", "countdown", "invitation", "advanced", 6, [_variant("countdown-variant-a", "Countdown A", "advanced", "invitation", 1)]),
    _component("comp_022", "map", "invitation", "core", 7, [_variant("map-variant-a", "Map A", "core", "invitation", 1)]),
    _component("comp_023", "rsvp", "invitation", "core", 8, [_variant("rsvp-variant-a", "RSVP A", "core", "invitation", 1)]),
    _component("comp_024", "timeline", "invitation", "advanced", 9, [_variant("timeline-variant-a", "Timeline A", "advanced", "invitation", 1)]),
    _component("comp_025", "faq", "invitation", "advanced", 10, [_variant("faq-variant-a", "FAQ A", "advanced", "invitation", 1)]),
    _component("comp_026", "footer", "invitation", "core", 11, [_variant("footer-variant-a", "Footer A", "core", "invitation", 1)]),
    _component("comp_027", "maintainer", "website", "premium", 16, [
        _variant("MTP1-Configurable-Maintainer", "Mantenedor configurable", "premium", "website", 1),
    ], name="Mantenedor"),
]


TEMPLATE_CATEGORY_SEEDS: List[Dict[str, Any]] = [
    {
        "id": "cat_001",
        "productType": "website",
        "categoryCode": "construction",
        "name": "Construcción",
        "description": "Templates para constructoras, obras y servicios relacionados.",
        "active": True,
        "sortOrder": 1,
        "allowedComponentCodes": ["navigation", "hero", "projects", "beforeAfter", "services", "process", "socialProof", "branches", "immersiveVideo", "youtubeVideo", "whatsapp_floating", "blankCanvas", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_002",
        "productType": "website",
        "categoryCode": "beauty",
        "name": "Belleza",
        "description": "Templates para belleza y bienestar.",
        "active": True,
        "sortOrder": 2,
        "allowedComponentCodes": ["navigation", "hero", "services", "socialProof", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_003",
        "productType": "website",
        "categoryCode": "technical_services",
        "name": "Servicios técnicos",
        "description": "Templates para servicios tecnicos y mantenimiento.",
        "active": True,
        "sortOrder": 3,
        "allowedComponentCodes": ["navigation", "hero", "services", "process", "socialProof", "branches", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_004",
        "productType": "website",
        "categoryCode": "restaurant",
        "name": "Restaurante",
        "description": "Templates para gastronomia.",
        "active": True,
        "sortOrder": 4,
        "allowedComponentCodes": ["navigation", "hero", "gallery", "services", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_005",
        "productType": "website",
        "categoryCode": "portfolio",
        "name": "Portafolio",
        "description": "Templates para profesionales creativos.",
        "active": True,
        "sortOrder": 5,
        "allowedComponentCodes": ["navigation", "hero", "projects", "gallery", "socialProof", "youtubeVideo", "whatsapp_floating", "content", "footer"],
    },
    {
        "id": "cat_006",
        "productType": "website",
        "categoryCode": "corporate",
        "name": "Corporativo",
        "description": "Templates para empresas.",
        "active": True,
        "sortOrder": 6,
        "allowedComponentCodes": ["navigation", "hero", "projects", "beforeAfter", "services", "process", "socialProof", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_007",
        "productType": "website",
        "categoryCode": "health",
        "name": "Salud",
        "description": "Templates para salud y bienestar.",
        "active": True,
        "sortOrder": 7,
        "allowedComponentCodes": ["navigation", "hero", "services", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_008",
        "productType": "website",
        "categoryCode": "education",
        "name": "Educación",
        "description": "Templates para educacion y cursos.",
        "active": True,
        "sortOrder": 8,
        "allowedComponentCodes": ["navigation", "hero", "services", "youtubeVideo", "whatsapp_floating", "content", "leadForm", "footer"],
    },
    {
        "id": "cat_009",
        "productType": "invitation",
        "categoryCode": "wedding",
        "name": "Wedding",
        "description": "Templates para bodas.",
        "active": True,
        "sortOrder": 1,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "countdown", "map", "rsvp", "timeline", "faq", "footer"],
    },
    {
        "id": "cat_010",
        "productType": "invitation",
        "categoryCode": "birthday",
        "name": "Birthday",
        "description": "Templates para cumpleaños.",
        "active": True,
        "sortOrder": 2,
        "allowedComponentCodes": ["intro", "hero", "details", "gallery", "countdown", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_011",
        "productType": "invitation",
        "categoryCode": "baby_shower",
        "name": "Baby shower",
        "description": "Templates para baby shower.",
        "active": True,
        "sortOrder": 3,
        "allowedComponentCodes": ["intro", "hero", "details", "gallery", "countdown", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_012",
        "productType": "invitation",
        "categoryCode": "graduation",
        "name": "Graduation",
        "description": "Templates para graduaciones.",
        "active": True,
        "sortOrder": 4,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "map", "rsvp", "footer"],
    },
    {
        "id": "cat_013",
        "productType": "invitation",
        "categoryCode": "corporate_event",
        "name": "Corporate event",
        "description": "Templates para eventos corporativos.",
        "active": True,
        "sortOrder": 5,
        "allowedComponentCodes": ["intro", "hero", "details", "timeline", "map", "rsvp", "faq", "footer"],
    },
    {
        "id": "cat_014",
        "productType": "invitation",
        "categoryCode": "baptism",
        "name": "Baptism",
        "description": "Templates para bautizos.",
        "active": True,
        "sortOrder": 6,
        "allowedComponentCodes": ["intro", "hero", "story", "details", "gallery", "map", "rsvp", "footer"],
    },
]


GENERAL_EXTRA_SEEDS: List[Dict[str, Any]] = [
    {"code": "custom_domain", "name": "Dominio propio", "productType": "website", "price": 1990, "priceMonthly": 1990, "currency": "CLP"},
    {"code": "extra_image", "name": "Imagen extra", "productType": "website", "price": 190, "priceMonthly": 190, "currency": "CLP"},
    {"code": "extra_video", "name": "Video extra", "productType": "website", "price": 990, "priceMonthly": 990, "currency": "CLP"},
    {"code": "premium_hero", "name": "Hero Premium", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "immersive_video", "name": "Video inmersivo premium", "productType": "website", "price": 3990, "priceMonthly": 3990, "currency": "CLP"},
    {"code": "dashboard_admin", "name": "Dashboard administrador", "productType": "website", "price": 4990, "priceMonthly": 4990, "currency": "CLP"},
    {"code": "analytics", "name": "Analytics", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "advanced_seo", "name": "SEO avanzado", "productType": "website", "price": 9990, "priceMonthly": 9990, "currency": "CLP"},
    {"code": "mercadopago", "name": "Integración MercadoPago", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "transbank", "name": "Integración Transbank", "productType": "website", "price": 2990, "priceMonthly": 2990, "currency": "CLP"},
    {"code": "priority_support", "name": "Soporte prioritario", "productType": "website", "price": 7990, "priceMonthly": 7990, "currency": "CLP"},
    {"code": "public_url_pdf", "name": "URL pública para PDF", "productType": "invitation", "price": 1990, "currency": "CLP"},
    {"code": "extra_video_invitation", "name": "Video extra", "productType": "invitation", "price": 1490, "currency": "CLP"},
    {"code": "dashboard_invitation", "name": "Dashboard administrador", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "trivia_game", "name": "Trivia pareja", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "puzzle_game", "name": "Puzzle", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "roulette_game", "name": "Ruleta", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "mini_adventure_game", "name": "Mini aventura", "productType": "invitation", "price": 5990, "currency": "CLP"},
    {"code": "custom_domain_invitation", "name": "Dominio propio", "productType": "invitation", "price": 1990, "priceMonthly": 1990, "currency": "CLP"},
    {"code": "extra_guests_50", "name": "50 invitados extra", "productType": "invitation", "price": 990, "currency": "CLP"},
    {"code": "advanced_rsvp", "name": "RSVP avanzado", "productType": "invitation", "price": 3990, "currency": "CLP"},
    {"code": "guest_analytics", "name": "Analytics invitados", "productType": "invitation", "price": 2990, "currency": "CLP"},
]


def empty_seed_stats() -> PricingSeedStats:
    return PricingSeedStats()
